from pathlib import Path
from datetime import datetime
import html
import re
import json

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    KeepTogether, HRFlowable
)
from reportlab.lib import colors

OUT = Path("reports")
OUT.mkdir(exist_ok=True)

STATUS_COLORS = {
    "PASS": colors.HexColor("#15803D"),
    "WARN": colors.HexColor("#B45309"),
    "REVIEW": colors.HexColor("#B45309"),
    "ERROR": colors.HexColor("#B91C1C"),
    "INFO": colors.HexColor("#2563EB"),
    "DETECTED": colors.HexColor("#7C3AED"),
    "SKIPPED": colors.HexColor("#64748B"),
    "AUTHORIZED": colors.HexColor("#2563EB"),
}


def esc(value):
    return html.escape(str(value or ""))


def lines(value):
    return [x.strip() for x in str(value or "").splitlines() if x.strip()]


def parse_structured_evidence(text):
    """Turn common scanner evidence into a compact key/value or status table."""
    rows = []
    for line in lines(text):
        pm = re.match(r"^(\d{1,5}/tcp)\s+(OPEN|CLOSED|FILTERED/UNKNOWN)(?:\s*\((\d+)\s*ms\))?\s*[—-]?\s*(.*)$", line, re.I)
        if pm:
            rows.append((pm.group(1), pm.group(2).upper(), ((pm.group(4) or "") + (f" · {pm.group(3)} ms" if pm.group(3) else "")).strip() or "—"))
            continue
        m = re.match(r"^(.+?)\s+(HTTP\s+)?(\d{3})(?:\s+|$)(.*)$", line, re.I)
        if m:
            left = m.group(1).strip()
            code = m.group(3)
            rest = m.group(4).strip()
            rows.append((left, code, rest or "—"))
            continue
        if ":" in line and len(line.split(":", 1)[0]) < 50:
            k, v = line.split(":", 1)
            rows.append((k.strip(), "", v.strip() or "—"))
    return rows[:80]


def status_badge(status):
    color = STATUS_COLORS.get(str(status).upper(), colors.HexColor("#475569"))
    return Table([[Paragraph(f"<b>{esc(status)}</b>", ParagraphStyle(
        "Badge", fontName="Helvetica-Bold", fontSize=7.5, leading=9,
        textColor=colors.white, alignment=TA_CENTER))]], colWidths=[20*mm], rowHeights=[6*mm],
        style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), color),
            ("BOX", (0, 0), (-1, -1), 0, color),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))


def draw_page(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setStrokeColor(colors.HexColor("#CBD5E1"))
    canvas.setLineWidth(0.5)
    canvas.line(15*mm, 11*mm, w-15*mm, 11*mm)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(15*mm, 7*mm, "Generated by Telegram Web Security Audit Bot")
    canvas.drawRightString(w-15*mm, 7*mm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(report, telegram_user, dev_name):
    target = report["target"]
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", target)[:80]
    filename = OUT / f"security_audit_{safe}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="CoverTitle", parent=styles["Title"], alignment=TA_CENTER,
                              fontSize=23, leading=27, textColor=colors.HexColor("#0F172A"), spaceAfter=5*mm))
    styles.add(ParagraphStyle(name="Subtitle", parent=styles["BodyText"], alignment=TA_CENTER,
                              fontSize=9.5, leading=13, textColor=colors.HexColor("#64748B")))
    styles.add(ParagraphStyle(name="Meta", parent=styles["BodyText"], fontSize=8.5, leading=12,
                              textColor=colors.HexColor("#334155")))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], fontSize=14, leading=18,
                              textColor=colors.HexColor("#0F172A"), spaceBefore=3*mm, spaceAfter=3*mm))
    styles.add(ParagraphStyle(name="CheckTitle", parent=styles["Heading3"], fontSize=11, leading=14,
                              textColor=colors.HexColor("#0F172A"), spaceAfter=1*mm))
    styles.add(ParagraphStyle(name="Small", parent=styles["BodyText"], fontSize=7.8, leading=10.5,
                              textColor=colors.HexColor("#334155")))
    styles.add(ParagraphStyle(name="Tiny", parent=styles["BodyText"], fontSize=6.8, leading=8.5,
                              textColor=colors.HexColor("#475569")))
    styles.add(ParagraphStyle(name="Evidence", parent=styles["BodyText"], fontName="Courier",
                              fontSize=6.6, leading=8.2, textColor=colors.HexColor("#334155")))

    doc = SimpleDocTemplate(str(filename), pagesize=A4,
                            rightMargin=15*mm, leftMargin=15*mm,
                            topMargin=15*mm, bottomMargin=17*mm,
                            title="Web Security Audit Report", author=str(dev_name))
    story = []

    # Cover / executive summary
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph("WEB SECURITY AUDIT REPORT", styles["CoverTitle"]))
    story.append(Paragraph("Professional technical assessment · HTTP, TLS, DNS, headers, exposure and configuration checks",
                           styles["Subtitle"]))
    story.append(Spacer(1, 7*mm))
    meta = [
        [Paragraph("<b>Target</b>", styles["Meta"]), Paragraph(esc(target), styles["Meta"])],
        [Paragraph("<b>Final URL</b>", styles["Meta"]), Paragraph(esc(report.get("final_url", "")), styles["Meta"])],
        [Paragraph("<b>Page title</b>", styles["Meta"]), Paragraph(esc(report.get("title") or "Not detected"), styles["Meta"])],
        [Paragraph("<b>Telegram user</b>", styles["Meta"]), Paragraph(esc(telegram_user), styles["Meta"])],
        [Paragraph("<b>Completed</b>", styles["Meta"]), Paragraph(esc(report.get("completed", "")), styles["Meta"])],
    ]
    mt = Table(meta, colWidths=[35*mm, 135*mm], hAlign="LEFT")
    mt.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#F1F5F9")),
        ("BOX", (0,0), (-1,-1), 0.6, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0,0), (-1,-1), 0.35, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 5), ("RIGHTPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 4), ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ]))
    story.append(mt)
    story.append(Spacer(1, 7*mm))

    s = report.get("summary", {})
    check_count = len(report.get("results", []))
    data = [
        ["CHECKS", "FINDINGS", "HIGH", "MEDIUM", "LOW"],
        [str(check_count), str(s.get("findings", 0)), str(s.get("high", 0)),
         str(s.get("medium", 0)), str(s.get("low", 0))]
    ]
    t = Table(data, colWidths=[34*mm]*5, rowHeights=[8*mm, 12*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,0), 7.5),
        ("FONTSIZE", (0,1), (-1,1), 16),
        ("FONTNAME", (0,1), (-1,1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0,1), (-1,1), colors.HexColor("#0F172A")),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]))
    story.append(t)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        "<b>Request pacing:</b> configurable delay/jitter and retry backoff are used to reduce load and improve reliability on slow or rate-limited sites. "
        "Active/destructive methods are not blindly executed; the report distinguishes observed responses from methods that were not actively probed.",
        styles["Small"]))
    story.append(Spacer(1, 7*mm))
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#CBD5E1")))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph("60-Check Coverage", styles["Section"]))
    catalog = report.get("scan_catalog", [])
    cov_rows = [[Paragraph("#", styles["Tiny"]), Paragraph("CHECK", styles["Tiny"]), Paragraph("STATUS", styles["Tiny"])]]
    result_by_scan = {int(x.get("scan", -1)): x for x in report.get("results", [])}
    for c in catalog:
        n = int(c.get("scan", -1))
        item = result_by_scan.get(n, {})
        cov_rows.append([Paragraph(f"{n:02d}", styles["Tiny"]), Paragraph(esc(c.get("name", "")), styles["Tiny"]), Paragraph(esc(item.get("status", "NOT RUN")), styles["Tiny"])])
    cov = Table(cov_rows, colWidths=[12*mm, 125*mm, 33*mm], repeatRows=1)
    cov.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID", (0,0), (-1,-1), 0.3, colors.HexColor("#CBD5E1")),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 4), ("RIGHTPADDING", (0,0), (-1,-1), 4),
        ("TOPPADDING", (0,0), (-1,-1), 2.5), ("BOTTOMPADDING", (0,0), (-1,-1), 2.5),
    ]))
    story.append(cov)
    story.append(PageBreak())
    story.append(Paragraph("Detailed Scan Results", styles["Section"]))

    for item in report.get("results", []):
        status = str(item.get("status", "INFO"))
        risk = str(item.get("risk", "INFO"))
        detail = str(item.get("detail", ""))
        evidence = str(item.get("evidence", ""))

        header = Table([
            [Paragraph(f"<b>#{item.get('scan', ''):02d} · {esc(item.get('name', ''))}</b>", styles["CheckTitle"]),
             status_badge(status),
             Paragraph(f"<b>Risk:</b> {esc(risk)}", styles["Tiny"])]
        ], colWidths=[115*mm, 24*mm, 31*mm])
        header.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ("BOX", (0,0), (-1,-1), 0.6, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
            ("LEFTPADDING", (0,0), (-1,-1), 5), ("RIGHTPADDING", (0,0), (-1,-1), 5),
            ("TOPPADDING", (0,0), (-1,-1), 4), ("BOTTOMPADDING", (0,0), (-1,-1), 4),
        ]))

        block = [header, Spacer(1, 1.5*mm),
                 Paragraph(f"<b>Result:</b> {esc(detail).replace(chr(10), '<br/>')}", styles["Small"])]

        structured = parse_structured_evidence(evidence)
        if structured:
            rows = [[Paragraph("ITEM", styles["Tiny"]), Paragraph("STATUS", styles["Tiny"]), Paragraph("DETAIL", styles["Tiny"])]]
            for a, b, c in structured:
                rows.append([Paragraph(esc(a), styles["Tiny"]), Paragraph(esc(b), styles["Tiny"]), Paragraph(esc(c), styles["Tiny"])])
            et = Table(rows, colWidths=[48*mm, 23*mm, 99*mm], repeatRows=1)
            et.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#E2E8F0")),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
                ("GRID", (0,0), (-1,-1), 0.35, colors.HexColor("#CBD5E1")),
                ("VALIGN", (0,0), (-1,-1), "TOP"),
                ("LEFTPADDING", (0,0), (-1,-1), 4), ("RIGHTPADDING", (0,0), (-1,-1), 4),
                ("TOPPADDING", (0,0), (-1,-1), 3), ("BOTTOMPADDING", (0,0), (-1,-1), 3),
            ]))
            block += [Spacer(1, 2*mm), Paragraph("<b>Observed evidence</b>", styles["Tiny"]), et]
        elif evidence:
            block += [Spacer(1, 1.5*mm), Paragraph("<b>Evidence</b>", styles["Tiny"]),
                      Paragraph(esc(evidence[:3000]).replace("\n", "<br/>"), styles["Evidence"])]

        block.append(Spacer(1, 4*mm))
        story.append(KeepTogether(block))

    story.append(PageBreak())
    story.append(Paragraph("Assessment Notes", styles["Section"]))
    story.append(Paragraph("Each result distinguishes observed evidence from heuristic or unconfirmed observations. Endpoint discovery uses non-authenticated HTTP checks; sensitive archive/configuration checks record response status without downloading potentially sensitive file bodies. State-changing HTTP methods and injection-style tests remain authorization-gated and are not blindly executed.", styles["Small"]))
    story.append(Spacer(1, 5*mm))
    story.append(Paragraph("Security Recommendations", styles["Section"]))
    recs = [
        "Review every WARN, REVIEW, or ERROR result and confirm whether the observed endpoint or configuration is intentional.",
        "Restrict administrative and management interfaces by authentication, authorization, network controls and MFA where appropriate.",
        "Do not expose backup archives, database dumps, source-control metadata, environment files or configuration backups over HTTP.",
        "Use HTTPS with modern TLS versions and a valid certificate chain; maintain HSTS and appropriate security headers.",
        "Review exposed API endpoints and documentation for authentication, authorization and information-disclosure controls.",
        "Keep CMS components, plugins, frameworks and dependencies updated and remove unused components.",
        "Use written authorization and a defined scope before enabling any active security testing against a system.",
    ]
    for i, rec in enumerate(recs, 1):
        story.append(Paragraph(f"<b>{i}.</b> {esc(rec)}", styles["BodyText"]))
        story.append(Spacer(1, 2.5*mm))
    story.append(Spacer(1, 15*mm))
    story.append(Paragraph(f"<b>Developer:</b> {esc(dev_name)}", ParagraphStyle("Dev", parent=styles["BodyText"], alignment=TA_CENTER, fontSize=9)))

    doc.build(story, onFirstPage=draw_page, onLaterPages=draw_page)
    return str(filename)
